# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build & Test & Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: 'Unit Tests'
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4

    - name: Switch to xcode 15.2
      run: sudo xcode-select --switch /Applications/Xcode_15.2.app

    - name: Test Swift Package
      run: xcodebuild test -scheme AsyncDataLoader -destination 'platform=iOS Simulator,OS=17.2,name=iPhone 15 Pro' -enableCodeCoverage YES -derivedDataPath .DerivedData/ clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        slug: alvinh77/async-data-loader
