name: Swift Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  swift-lint:
    name: 'Swift Lint'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Swift Lint Check
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict