name: Tests & Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    name: 'Unit Tests'
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4

    - name: Switch to xcode 15.2
      run: sudo xcode-select --switch /Applications/Xcode_15.2.app

    - name: Test Swift Package
      run: |
        xcodebuild test -scheme AsyncDataLoader -destination 'platform=iOS Simulator,OS=17.2,name=iPhone 15 Pro' -enableCodeCoverage YES -derivedDataPath .DerivedData/ clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        pathCoverage=.DerivedData/Build/ProfileData/*/Coverage.profdata
        output=.DerivedData/Build/Products/Debug-iphonesimulator/AsyncDataLoader.o
        xcrun llvm-cov export -format="lcov" -instr-profile $pathCoverage $output > info.lcov
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        slug: alvinh77/async-data-loader